[env]
TERM = "xterm-256color"

[font]
[font.normal]
family = "MapleMono"
size =13 

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "R"
mods = "Control|Shift"




[window]
blur = true
decorations = "none"
opacity = 1
startup_mode = "Maximized"

[window.dimensions]
columns = 170
lines = 40

[window.padding]
x = 25
y = 25
